### ISSUE TITLE
Second zone not visible

### ISSUE THREAD

**Issue by ddaemon82** [floringhimie/salusfy#2]
Hello,

Thank you for this integration! It is working with my IT500 thermostat nice.

I also have a second sensor IT300, which shows up in the 
ajax_device_values.php

"CH2currentRoomTemp"
,"CH2currentSetPoint":
","CH2heatOnOffStatus":" etc

Is there a way to run double instance of your component? because just changing the readout variable names I have valid data for upstairs floor

I tried to double in your code the functions and variables for second channel, but still I can not use it as a second, or double thermostat.

**Comment by floringhimie** [comment]
Hi,
I believe in your output you have second zone, I have no idea how this look also in the salus-it500.com page(with multiple zones).
It should work if you duplicate the code in second integration (something like salusfy2) but you should also change the code inside the climate.py and try to change the "Z1" (from current_tempZ1_set, current_tempZ1, auto_setZ1) to "Z2" and also where you find "CH1" to "CH2" (from CH1currentSetPoint, CH1currentRoomTemp, CH1heatOnOffStatus, CH1heatOnOff).

So try to duplicate the salusfy folder from custom_components to salusfy2, make the above changes and add also in configuration.yaml second climate:
climate:
  - platform: salusfy2
    username: "EMAIL"
    password: "PASSWORD"
    id: "DEVICEID"

This is a dirty fix... and it is possible to make salus-it500.com server to block IP address due to flood.
Second way to fix this issue will be to make the component adapting to x zone and for each zone to create a climate...but this my friend I cannot help you with with my Python knowledge...

Thank you and sorry!

**Comment by ddaemon82** [comment]
Thanks, that is what I just tried to do, but had no success for some reason.

Maybe someone out there has a similar issue and they will be able to help...

If I figure out in the meantime, I will let you know how this could be solved.

This is more a wish, not an issue. Should I close the issue?

**Comment by ddaemon82** [comment]
I managed to do it after all!
Both integrations should be under ONE climate statement. That seemed to be my problem I think.
THanks for the good work you did!

climate:
   - platform: salusfy
    username: "EMAIL"
    password: "PASSWORD"
    id: "DEVICEID"
    
  -  platform: salusfy2
    username: "EMAIL"
    password: "PASSWORD"
    id: "DEVICEID"
